### PR TITLE
Fix config storage module name in README.md

### PR DESCRIPTION
**Pull request by michallepicki**

### CODE REVIEW

**Comment by michallepicki** [comment]
Also, should I use the https://github.com/almirsarajcic/waffle_gcs repository instead? The published hex package doesn't have all the features I need.

**Comment by tyler-eon** [comment]
@michallepicki  Yes, the repo you linked to has officially taken over for this one. I'm not sure if they've pushed a new update to hex.pm yet but unfortunately I don't have the time even just to help manage this project let alone helm it, so I've passed the baton to @almirsarajcic .

If hex.pm doesn't have a package published pointing to the new updates I would recommend having hex pull from github to grab the latest version from the @almirsarajcic fork.

**Comment by michallepicki** [comment]
@tyler-eon Cool, thanks for the info. Do you plan on sending your changes (e.g. gapi 0.14 upgrade) upstream?

**Comment by tyler-eon** [comment]
That's really up to the new maintainers to decide. They can cherry-pick the edits if they'd like or rewrite it in their own style, either way is good.

**Pull request closed without merging**
